### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by ghost**
After the format was organized a few of the files had the wrong
order/value for the headings, thus the position was slightly off.
Updated all headings to be the same across all files, and re-ordered
them into the order the correct files were. Technically c10 is still
missing the ADV section, but that’s a duplicate section anyway and
already resides within the Dialogue .txt file. Maybe one day I’ll move
it.

### CODE REVIEW

**Comment by zeromus-hf** [comment]
I see changes to subtitles that are not just header changes. Is this intended?

**Comment by ghost** [comment]
@zeromus-hf I think so, the only subtitles that should have changed are because I'm moving one section of subtitles into a different section of the document, so it's basically swap out two lines for two new lines, there should be no single line swaps basically (where I am keeping the Japanese but changing the English).

**Comment by zeromus-hf** [comment]
Ah so your version simply isn't formatted. Well I whipped this up: http://psycoframe.space:5001/index

It's a web interface for the script that I think will prove useful. It'll output errors and such just like the command line variant. Can you re-do the branch but before overwriting the files, format and commit them in this branch. Then take your new changes, format *them*, and then overwrite. That way your diff is a diff between two formatted files and it will only display your real changes.

Tell me how that goes.

**Comment by zeromus-hf** [comment]
If it's confusing then I can do it. Basically you're making sure that before and after your changes the file is normalized to one specific formatting.

**Pull request closed without merging**
